// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBqeOU90NFYL-QOxD3w7leYrRiDbbhNoo',
    appId: '1:208198550748:web:d7f6507923610af2d6a019',
    messagingSenderId: '208198550748',
    projectId: 'my-goals-3f688',
    authDomain: 'my-goals-3f688.firebaseapp.com',
    storageBucket: 'my-goals-3f688.appspot.com',
    measurementId: 'G-1L4ZFF5YEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxIixqJfLb1hRwH9qfQtTQl8PeqqaD510',
    appId: '1:208198550748:android:22fa5a7cf06970bbd6a019',
    messagingSenderId: '208198550748',
    projectId: 'my-goals-3f688',
    storageBucket: 'my-goals-3f688.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyZ-wU37Rv1-JdW1WQlhnEMHGN0w37GLg',
    appId: '1:208198550748:ios:f42a705d7bfd82d3d6a019',
    messagingSenderId: '208198550748',
    projectId: 'my-goals-3f688',
    storageBucket: 'my-goals-3f688.appspot.com',
    iosBundleId: 'com.chinrust.myGoals',
  );
}
